### ISSUE TITLE
Error with Gnome 3.34.4 on Arch Linux

### ISSUE THREAD

**Issue by ritterdaniel** [atareao/disk-usage-space#1]
When I try to enable this extension via extensions.gnome.org it fails with the following error message:

`Feb 20 20:46:01 pluto gnome-shell[1475]: JS ERROR: Extension disk-space-usage@atareao.es: TypeError: this.update is not a function
                                         DiskSpaceUsageButton@/home/daniel/.local/share/gnome-shell/extensions/disk-space-usage@atareao.es/extension.js:84:9
                                         enable@/home/daniel/.local/share/gnome-shell/extensions/disk-space-usage@atareao.es/extension.js:234:28
                                         _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                         _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:415:13
                                         _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:412:9
                                         _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:529:61
                                         enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:175:13
                                         callback@resource:///org/gnome/shell/ui/extensionDownloader.js:233:22
                                         gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
`
You can find the full log [here](https://gist.github.com/dan1707/5b7b5828d9e79124d8aedbc8650b4565).

**Comment by atareao** [comment]
Fixed
